[options]
brcobranca_api_url = http://boleto_cnab_api:9292
server_wide_modules = web,queue_job,module_change_auto_install
load_language = pt_BR
modules_auto_install_disabled = l10n_br_website_sale,l10n_br_sales
